### ISSUE TITLE
Problem toolbar = full

### ISSUE THREAD

**Issue by jorge-1409** [egeloen/IvoryCKEditorBundle#108]
composer.json

```
"egeloen/ckeditor-bundle": "dev-master",
```

config.yml

```
ivory_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: full
```

![](https://googledrive.com/host/0B5kD5dDiZVDyNDB0Wjdtd3ItOTQ)

The problem is possibly: ckeditor.js  [Upgrade CKEditor to 4.4.1 commit]
