### ISSUE TITLE
Don't display some toolbars items

### ISSUE THREAD

**Issue by pk16011990** [egeloen/IvoryCKEditorBundle#109]
Hi,

i try config custom toolbar, but some items don't display. For example justifyClasses. 

My config:

```
ivory_ck_editor:
  default_config: default
  configs:
    default:
      toolbar: 
        - ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']
        - ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
        - ['NumberedList', 'BulletedList', '-', 'CreateDiv', '-', 'AlignLeft', 'AlignCenter', 'AlignRight', 'AlignJustify']
        - ['Link', 'Unlink']
        - ['Image', 'Flash', 'Table', 'SpecialChar']
        - '/'
        - ['Styles', 'Format', 'Font', 'FontSize']
        - ['Maximize', '-', 'Source', '-','Save', 'Preview']
```
