### ISSUE TITLE
PHPUnit raises an error on a non-existent "templating.engines" parameter

### ISSUE THREAD

**Issue by feelic** [egeloen/IvoryCKEditorBundle#111]
Hello,
PHP unit raises an error that i think might either be linked to the CKEditorBundle or something in my configuration.
**Here is the error :**

```
1) Feelic\FrontBundle\Tests\Controller\DefaultControllerTest::testIndex
Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "templating.engines".

/var/www/ct/Symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:106
/var/www/ct/Symfony/app/bootstrap.php.cache:1955
/var/www/ct/Symfony/vendor/egeloen/ckeditor-bundle/Ivory/CKEditorBundle/DependencyInjection/IvoryCKEditorExtension.php:58
/var/www/ct/Symfony/vendor/egeloen/ckeditor-bundle/Ivory/CKEditorBundle/DependencyInjection/IvoryCKEditorExtension.php:41
/var/www/ct/Symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ConfigurableExtension.php:35
/var/www/ct/Symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php:50
/var/www/ct/Symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
/var/www/ct/Symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:117
/var/www/ct/Symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:619
/var/www/ct/Symfony/app/bootstrap.php.cache:2492
/var/www/ct/Symfony/app/bootstrap.php.cache:2271
/var/www/ct/Symfony/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php:47
/var/www/ct/Symfony/src/Feelic/FrontBundle/Tests/Controller/DefaultControllerTest.php:11
```

**The test goes as follows :**

``` php
<?php

namespace Feelic\FrontBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/login');

        $buttonCrawlerNode = $crawler->selectButton('submit');

        $form = $buttonCrawlerNode->form(array(
            '_username' => 'username',
            '_password' => 'password',
        ));
    }
}
```

**And in app/config.yml i have the templating.engines properly set :**

``` yml
framework:
    #esi:             ~
    translator:      { fallback: "en" }
    default_locale: en
    secret:          "%secret%"
    router:         
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ['127.0.0.1', '10.0.0.1'] # a list of proxy IPs you trust
    session:        ~
```

**I have found a reference to "templating.engines" that i believe has PHPUnit raising the error in :**

> https://github.com/egeloen/IvoryCKEditorBundle/blob/master/DependencyInjection/IvoryCKEditorExtension.php

What could be causing this error  ? (the application and IvoryCKEditorBundle works a wonder besides this)

Thank you,

Feelic
