### ISSUE TITLE
How to add plugin configuration?

### ISSUE THREAD

**Issue by cassianotartari** [egeloen/IvoryCKEditorBundle#125]
Hello!

   I'm trying to figure out how to add a plugin configuration without success. Is there any option for this?

   For example: I would like to set true the char counting with html and white spaces. In the plugin page http://ckeditor.com/addon/wordcount says:

``` js
config.wordcount = {

    // Whether or not you want to show the Word Count
    showWordCount: true,

    // Whether or not you want to show the Char Count
    showCharCount: false,

     // Whether or not to include Html chars in the Char Count
     countHTML: false
};
```

I've tried to add inline:

``` php
                  ->add('description', 'ckeditor', array(
                        'required' => false,
                        'config' => array(
                            'showCharCount' => 'true'
                        ))
                    )
```

No effect, tried in configuration with:

```
ivory_ck_editor:
    default_config: my_config
    plugins:
        wordcount:
            path:     "/bundles/myadmin/ckeditor/wordcount/"
            filename: "plugin.js"
    configs:
        my_config:
            extraPlugins: "wordcount"
            language:  '%locale%'
            toolbar:   ...
            config.wordcount:
                    showCharCount: true
```

Is it possible to add this configuration?

Thanks!
