### ISSUE TITLE
helios-ag/FMElfinderBundle 3.0

### ISSUE THREAD

**Issue by smatyas** [egeloen/IvoryCKEditorBundle#128]
Hi,

a little improvement: I've just tested your bundle using "helios-ag/fm-elfinder-bundle": "3.0" requirement, and it also works very well for me. 
Minor changes in the minumum configuration should be added according to the FMElfinderBundle configs:

Instead of

```
fm_elfinder:
    editor: ckeditor
    connector:
        roots:
            uploads:
                path: uploads
```

the following should be used:

```
fm_elfinder:
    instances:
        ckeditor:
            editor: ckeditor
            compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
```

Thanks for you work! :smiley: :+1:
