### ISSUE TITLE
Adding the Page Break Plugin

### ISSUE THREAD

**Issue by dawidvdh** [egeloen/IvoryCKEditorBundle#133]
Hello, Excellent work with this bundle. I am just having one slight problem... I cant seem to be able to install the pagebreak plugin.

I have followed your [guide](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/usage.md#register). with no luck, i downloaded the plugin from [here](http://ckeditor.com/addon/pagebreak).

Here is my current config:

```
ivory_ck_editor:
    default_config: default

    plugins:
        fakeobjects:
            path:     "/bundles/webweb/ckeditor/fakeobjects/"
            filename: "plugin.js"
        pagebreak:
            path:     "/bundles/webweb/ckeditor/pagebreak/"
            filename: "plugin.js"

    configs:
        default:
            extraPlugins: "fakeobjects,pagebreak"
            toolbar: standard
            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
        jam_ck_toolbar:
            toolbar: "jam_ck_toolbar"
            # ...
    toolbars:
        configs:
            jam_ck_toolbar: [ "@document"]
        items:
            document: [ "Bold", "-", "Italic", "-", "Pagebreak" ]
```

Any Help would be Geatly Appreciated.
