### ISSUE TITLE
Multiple element style for YML config

### ISSUE THREAD

**Issue by picks44** [egeloen/IvoryCKEditorBundle#173]
How do I set a multiple element style in yml ?
I tried `- { name: "Button (link)", element: [ 'a', 'span' ] , attributes: { class: "btn btn-red" }}` but it raises an error

**Comment by egeloen** [comment]
Are you talking about https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/usage.md#stylesset-support ?

**Comment by cordoval** [comment]
bump @picks44

**Comment by egeloen** [comment]
@picks44 I don't find in the doc an example which uses multiple element. Can you point me the doc?

**Comment by picks44** [comment]
In the PHP builder 
```
$builder->add('field', 'ckeditor', array(
    'config' => array(
        'stylesSet' => 'my_styles',
    ),
    'styles' => array(
        'my_styles' => array(
            array('name' => 'CSS Style', 'element' => 'span', 'attributes' => array('class' => 'my_style')),
            array('name' => 'Multiple Element Style', 'element' => array('h2', 'span'), 'attributes' => array('class' => 'my_class')),
        ),
    ),
));
```

**Comment by egeloen** [comment]
I just give a try and the following works for me:

```
ivory_ck_editor:
    default_config: "config"
    configs:
        config:
            stylesSet: my_style
    styles:
        my_style:
            - { name: "Multiple Element Style", element: [ h2, span ], attributes: { class: my_class }}
```
