### ISSUE TITLE
Problem configuration CKEditor whit admingenerator and translation

### ISSUE THREAD

**Issue by rpostolov** [egeloen/IvoryCKEditorBundle#187]
Hi everyone !

I'm using CKEditor with AdminGenerator (the new version 'GeneratorBundle') and translation. But the editor doesn't appear and i have an issues with the parameter 'config_name'.

Here is my configuration :

PageAdmin-generator.yml
```

      translations:
          label:              global.translations            
          formType:           a2lix_translations_gedmo
          addFormOptions:
              fields:
                  titreH1:                    
                      label:  Title H1
                  titreH2:                    
                      label:  Title H2
                  resume:                    
                      label:  Short description
                  contenu:                    
                      label:  content 
                      formType: ckeditor    
                      config_name: 'basic_img'
```

config.yml
```
ivory_ck_editor:
    configs:

        basic:
            toolbar:  basic  
        basic_img:
            toolbar:  basic_img              
        simple:
            toolbar:  simple 
            
    toolbars:
        configs:
            basic: [ [ "Source" , "-" , "Save" , "Undo" , "Redo",  "-" , "Bold" ,  "Italic" , "Underline" , "Strike" , "Subscript" , "Superscript" , "-" ,  "Format" , "NumberedList", "BulletedList", "-" , "Link" , "Unlink" , "Anchor" , "-" , "RemoveFormat" , "Maximize" ] ]
            basic_img: [ [ "Source" , "-" , "Save" , "Undo" , "Redo" , "-", "JustifyLeft" , "JustifyCenter" , "JustifyRight" , "JustifyBlock" , "-" , "Bold" ,  "Italic" , "Underline" , "Strike" , "Subscript" , "Superscript", JustifyLeft , "-" ,  "Format" , "NumberedList", "BulletedList", "-" , "Image" , "-" , "Link" , "Unlink" , "Anchor" , "-" , "RemoveFormat" , "Maximize" ] ]           
            simple: [ [ "Undo" , "Redo",  "-" , "Bold" ,  "Italic" , "Underline" , "Strike" ] ]                       
            demo: [ [ "Source" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]    
```

Can someone help me please ? I'm stuck with this problem 4 days...

Thanks a lot and have a nice day !

**Comment by egeloen** [comment]
I have never used the admin generator :s So hard to say. Something strange to me:

```
contenu:                    
    label:  content 
    formType: ckeditor    
    config_name: 'basic_img' <-- HERE
```

It seems you want to use a ckeditor config name here but you can put form option directly on the `contenu` node in the admin generator? There is no `formOptions` as there is a `formType`?
