### ISSUE TITLE
[Config] Plugin names should not be normalized.

### ISSUE THREAD

**Issue by ju1ius** [egeloen/IvoryCKEditorBundle#190]
Hi,
The Symfony Config component normalizes plugin names, leading to 404 errors.

Given I have a plugin named 'my-plugin'
And the following configuration:

```yaml
# app/config.yml
ivory_ck_editor:
    plugins:
        my-plugin:
            path: /assets/cke/plugins/my-plugin/
            filename: plugin.js
    configs:
        my_config:
            extraPlugins: 'my-plugin'
```
The ckeditor config output will be:
```js
CKEDITOR.plugins.addExternal('my_plugin', '/assets/cke/plugins/my-plugin/', 'plugin.js');
```
Notice [the difference](http://symfony.com/doc/current/components/config/definition.html#normalization) ?
> The normalization process is used to remove some of the differences that result from different configuration formats, mainly the differences between YAML and XML.
> The separator used in keys is typically _ in YAML and - in XML. For example, auto_connect in YAML and auto-connect in XML. The normalization would make both of these auto_connect.

> The target key will not be altered if it's mixed like foo-bar_moo or if it already exists.

So I guess a good move would be to add a "name" key for the plugin config that can be safely used to reference the plugin in javascript.

```php
// IvoryCKEditorBundle/DependencyInjection/Configuration.php
/**
 * Creates the plugins node.
 *
 * @return \Symfony\Component\Config\Definition\Builder\NodeDefinition The plugins node.
 */
private function createPluginsNode()
{
    return $this->createNode('plugins')
        ->useAttributeAsKey('id')
        ->prototype('array')
            ->children()
                ->scalarNode('name')->end()
                ->scalarNode('path')->end()
                ->scalarNode('filename')->end()
            ->end()
        ->end();
}
```
