### ISSUE TITLE
setting enable: false throws ConfigManagerException

### ISSUE THREAD

**Issue by lordrhodos** [egeloen/IvoryCKEditorBundle#193]
I am using the bundle in conjunction with the "sonata-project/formatter-bundle" in version 2.5.2 but I have updated the composer file and tested this with version 3.0.1 as well. Same effect.

My config looks like this:

```
ivory_ck_editor:
    #autoload: false
    enable: false

    default_config: default
    configs:
        default:
            # default toolbar plus Format button
            toolbar:
                - [Bold, Italic, Underline, -, NumberedList, BulletedList, -, Outdent, Indent, -, Blockquote, -, Image, Link, Unlink]
                - [Templates, Format, Styles]
                - [Maximize, Source]

            format_tags: 'p;h1;h2;h3;h4;div'
            language: en
```

When I open the page with the integrated editor it throws an ConfigManagerException with the following error: `The CKEditor config "default" does not exist.`
