### ISSUE TITLE
How to use CKEditor Widget?

### ISSUE THREAD

**Issue by KillianLeroux** [egeloen/IvoryCKEditorBundle#203]
Hi,

First of all thanks for your bundle and happy new year!

I try to use the plugin ckeditor "Widget" (http://ckeditor.com/addon/widget) in stylesSet but it doesn't work :/

Here's what I did:

## 1. Create Widget
I followed this tutorial: http://docs.ckeditor.com/#!/guide/widget_sdk_tutorial_1
My plugin "simplebox" works with the toolbar button.

The plugin.js code is the same that: https://github.com/ckeditor/ckeditor-docs-samples/blob/master/tutorial-simplebox-1/simplebox/plugin.js

## 2. Add in stylesSet dropdown
I had this documentation line in my config.yml:

```yml
- { name: "Widget Style", type: "widget", widget: "simplebox", attributes: { class: "my_widget_style" }}
```

But "Widget Style" doesn't appear in my styleSet dropdown, no error message, what's happening?

### My config.yml:

```yml
# ckeditor
ivory_ck_editor:
    default_config: ckeditor_config
    plugins:
        lineutils:
            path:       "/bundles/lparticle/ckeditor/plugins/lineutils/"
            filename:   "plugin.js"
        widget:
            path:       "/bundles/lparticle/ckeditor/plugins/widget/"
            filename:   "plugin.js"
        simplebox:
            path:       "/bundles/lparticle/ckeditor/plugins/simplebox/"
            filename:   "plugin.js"
    configs:
        ckeditor_config:
            toolbar:        [ [ 'Preview', 'Simplebox' ], [ 'Cut','Copy','Paste','PasteText','-','Undo','Redo' ], [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ], "/", [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ], [ 'NumberedList','BulletedList','-','Outdent','Indent','-','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], [ 'Link','Unlink','Anchor' ], [ 'pbckcode','Image','Video','Table','SpecialChar' ], '/', [ 'Styles', 'Format','Font','FontSize' ], [ 'TextColor','BGColor' ], [ 'RemoveFormat' ], [ 'Maximize' ] ]
            uiColor:        "#dddddd"
            stylesSet:      styles_contenus
            contentsCss:    ['/bundles/lparticle/styles/styles_contenus.css']
            extraPlugins:   'widget,lineutils,simplebox'
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []

    styles:
        styles_contenus:
            - { name: "Texte 2 colonnes", element: "div", attributes: { class: "contenu_texte_2_col" }}
            - { name: "Widget Style", type: "widget", widget: "simplebox", attributes: { class: "my_widget_style" }}
            - { name: "Vidéo", element: "div", attributes: { class: "contenu_video" }}
```

### My buildForm configuration:

```yml
->add('corps', CKEditorType::class, array(
                'label' => 'Corps',
                'required' => false,
                'config_name' => 'ckeditor_config'
            ))
```

If you need further information do not hesitate!

Thanks :)

**Comment by egeloen** [comment]
Have you enable all its dependencies too? Basically, the main point about plugin not working is usually a bad config or missing dependency. Can you double check? If it still does not work, I will need to give it a try in my fork.

**Comment by KillianLeroux** [comment]
Yes I have all dependencies:
"lineutils" and "clipboard" ("clipboard" is in plugins core) for "widget" and "widget" for "simplebox".
And I check my configuration many times :/

In principle with the code I gave above you should reproduce the problem.

The CKEditor plugins are:
Line Utiles: http://ckeditor.com/addon/lineutils
Widget: http://ckeditor.com/addon/widget
Simplebox: https://github.com/ckeditor/ckeditor-docs-samples/blob/master/tutorial-simplebox-1/simplebox/plugin.js
Tutorial: http://docs.ckeditor.com/#!/guide/widget_sdk_tutorial_1

I remain available for any further information :)

Thanks!

**Comment by egeloen** [comment]
Thanks your for your detailled report! I will need to give a try to this plugin and see what's going on...

**Comment by KillianLeroux** [comment]
Good luck and thanks! :)

**Comment by egeloen** [comment]
So, I have give a try to it and everything is working, You can see it in action in my fork: https://github.com/egeloen/symfony-standard/compare/ckeditor...ckeditor-simplebox

Before explaining the issue in your code, take a look to http://ckeditor.com/tmp/4.4.0/widget-styles.html in order to see it in action and so well understand how it works.

The problem in your code is very minimal, you must use the simplebox class for the attribute stylesSet:

```
ivory_ck_editor:
    styles:
        default:
            - 
                name: "Widget Style"
                type: "widget"
                widget: "simplebox"
                attributes: { class: "simplebox" } # <- Here is the problem
```
