### ISSUE TITLE
custom html tags removed

### ISSUE THREAD

**Issue by hero789** [egeloen/IvoryCKEditorBundle#207]
i have 2 problems  :
1-the some html tags  `<body>,<head>,<footer>,<container>`
 have been removed from the editor content , i searched  for the problem onlline and found that it's ccan be fixed with  configuration parameter "Full page edit mode" `FCKConfig.FullPage = true` however i  don't know how to set it in the bundle edition .
2- setting config `toolbar: basic or full` has no effect at all .

**Comment by egeloen** [comment]
Hey!

1. I'm not aware of FCKConfig global object in CKEditor. Can you point me the doc?
2. Strange... Need to a try to it...

**Comment by egeloen** [comment]
I just give a try to your issue and the following config is working fine for me:

``` yaml
ivory_ck_editor:
    default_config: "default"
    configs:
        default:
            toolbar:        "full"
            allowedContent: true
```

The full toolbar is well used automatically by default and with the `allowedContent` option I'm able to keep all extra tags the CKEditor ACF would not accept but be aware the ACF is not here for nothing...

An other alternative is not enabled extra allowed content:

``` yaml
ivory_ck_editor:
    default_config: "default"
    configs:
        default:
            toolbar:             "full"
            extraAllowedContent: "body head footer container"
```

Here, we don't disable the ACF but extend it...
