### ISSUE TITLE
Attr class dont set

### ISSUE THREAD

**Issue by benblub** [egeloen/IvoryCKEditorBundle#251]
Classes or Divs dont work for me, Toolbar works. Any idea what wrong?

``` yaml
ivory_ck_editor:
    default_config: default
    configs:
        default:
            stylesSet: "my_styles"
        styles:
            my_styles:
                - { name: "CSS Style", element: "div", attributes: { class: "my_style" }}
                - { name: "CSS Style", element: "p", attributes: { class: "my_style" }}
                - { name: "CSS Style", element: "img", attributes: { class: "my_style" }}
            toolbar: [ [ "Bold", "-", "BulletedList", "-", "Link", "-", "Unlink", "-", "Image" , "-", "Maximize" ] ]
            allowedContent: true
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: default
                bodyClass:
                    enterMode: CKEDITOR.ENTER_DIV
```

**Comment by egeloen** [comment]
Hum, your configuration is not correct. You have put everything under the `configs` node whereas the `styles` node is a dedicated one. So, a valid yaml configuration would look like:

``` yaml
ivory_ck_editor:
    default_config: default
    configs:
        default:
            stylesSet: "my_styles"
    styles:
        my_styles:
            - { name: 'Blue Title', element: 'h2', styles: { 'color': 'Blue' }}
            - { name: 'Red Title' , element: 'h3', styles: { 'color': 'Red' }}
            - { name: 'CSS Style', element: 'span', attributes: { 'class': 'my_style' }}
            - { name: 'Marker: Yellow', element: 'span', styles: { 'background-color': 'Yellow' }}
```

I just give a try to this configuration and everything is working fine.

**Comment by benblub** [comment]
if i use this Config and add some text the p Tags has still no classes added.

ivory_ck_editor:
    default_config: default
    configs:
        default:
            stylesSet: "my_styles"
    styles:
        my_styles:
            - { name: 'Blue Title', element: 'h2', styles: { 'color': 'Blue' }}
            - { name: 'Red Title' , element: 'h3', styles: { 'color': 'Red' }}
            - { name: 'CSS Style', element: 'p', attributes: { 'class': 'my_style' }}
            - { name: 'Marker: Yellow', element: 'span', styles: { 'background-color': 'Yellow' }}

**Comment by egeloen** [comment]
To be honest, I just give a try to it and see items in the styles dropdown, so, I assume it is right... The styles have been implemented this way:

You define a style:

```
ivory_ck_editor:
    default_config: default
    configs:
        default:
            stylesSet: "my_styles"
    styles:
        my_styles:
            - { name: 'Blue Title', element: 'h2', styles: { 'color': 'Blue' }}
            - { name: 'Red Title' , element: 'h3', styles: { 'color': 'Red' }}
```

When rendering the CKEditor widget, the bundle will render them via:

```
CKEdItor.stylesSet.add('my_styles', [{'...'}, {'...'}]);
```

Then, the configs which relies on `stylesSet: "my_styles"` will link the styles to your CKEditor instance. According to this doc (http://docs.ckeditor.com/#!/guide/dev_styles) using this approach is valid and if there is something wrong it should been reported to the CKEditor team.
