### ISSUE TITLE
Attr class removed by CKeditor

### ISSUE THREAD

**Issue by jbracoupeau** [egeloen/IvoryCKEditorBundle#252]
Hey guys, I have a problem, CKEditor removes attr "class" from the content, even if I added allowedContent: true in my config.  All the rest of my config works fine, any idea ?

When I past code with classes, it saves it in my db with the classes, but if I want to edit the code, then classes are gone :/

# CKEditor
```
ivory_ck_editor:
    configs:
        my_config:
            toolbar: [ ["Maximize", "-", "Source", "-", "Save"], .....]
            uiColor: "#FFFFFF"
            allowedContent: true
```
