### ISSUE TITLE
Installed plugin not showing

### ISSUE THREAD

**Issue by sergiu-popa** [egeloen/IvoryCKEditorBundle#266]
Hello,

I'm trying to use YouTube Plugin (http://ckeditor.com/addon/youtube). I read the documentation here http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/plugin.html but the button does not appear in the toolbar. Here is my config:

```
ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar: standard
            extraPlugins: "youtube"
    plugins:
        youtube:
            path: "/ckeditor/plugins/youtube/"
            filename: "plugin.js"
```

The output is correct:
```
<script type="text/javascript">var CKEDITOR_BASEPATH = "/bundles/ivoryckeditor/";</script>
<script type="text/javascript" src="/bundles/ivoryckeditor/ckeditor.js"></script>
<script type="text/javascript">
if (CKEDITOR.instances["article_content"]) { delete CKEDITOR.instances["article_content"]; }
                    CKEDITOR.plugins.addExternal("youtube", "/ckeditor/plugins/youtube/", "plugin.js");
             
        var ivory_ckeditor_article_content = CKEDITOR.replace("article_content", {"toolbar":[["Cut","Copy","Paste","PasteText","PasteFromWord","-","Undo","Redo"],["Scayt"],["Link","Unlink","Anchor"],["Image","Table","HorizontalRule","SpecialChar"],["Maximize"],["Source"],"\/",["Bold","Italic","Strike","-","RemoveFormat"],["NumberedList","BulletedList","-","Outdent","Indent","-","Blockquote"],["Styles","Format","About"]],"extraPlugins":"youtube","language":"ro"});
ivory_ckeditor_article_content.on('change', function() { ivory_ckeditor_article_content.updateElement(); });
</script>
```

*plugin.js* can the viewed correctly at domain.com/ckeditor/plugins/youtube/plugin.js

What could be the problem? Do I need to specify manually all the buttons instead of using the standard toolbar?

Thank you
