### ISSUE TITLE
Customize the toolbar

### ISSUE THREAD

**Issue by ben29** [egeloen/IvoryCKEditorBundle#267]
Hi.
i'm using the last version of symfony 3.2 with form builder.
i try to Customize the toolbar to basic. but it's still showing the full toolbar.

my config.yml:

```
 ivory_ck_editor:
    configs:
        my_config:
            toolbar: basic
```

form builder:

```
 ->add('content', CKEditorType::class, array(
 'config' => array('toolbar' => 'standard'),
 ))
```

also try like this:

```
>add('content', CKEditorType::class, [
'autoload' => true,
 'input_sync' => true,
 'attr' => ['rows' => 20],
 'config' => array(
 'toolbar' => 'standard',
 'uiColor' => '#ffffff',
  ),
'label' => 'label.content',
 ])
```

thanks!
