### ISSUE TITLE
Multiple extra plugins path error

### ISSUE THREAD

**Issue by davidromani** [egeloen/IvoryCKEditorBundle#287]
Symfony version 2.8.20
Bundle version 4.0.6

If I only load one plugin all works well, but if I try to load multiple plugins there is a JS resource path problem:

```yaml
ivory_ck_editor:
    inline: false
    default_config: "my_config"
    configs:
        my_config:
            toolbar: "my_toolbar_1"
            extraPlugins: "youtube,uploadimage"
    toolbars:
        configs:
            my_toolbar_1:
                # (...)
    plugins:
        youtube:
            path:     "/bundles/<MY_BUNDLE>/js/youtube/"
            filename: "plugin.js"
        uploadimage:
            path:     "/bundles/<MY_BUNDLE>/js/uploadimage/"
            filename: "plugin.js"
```

Ckeditor is trying to load the last plugin (**always**) in this missing path:

```
"http://<MY_APP>/bundles/ivoryckeditor/plugins/uploadwidget/plugin.js?t=G87E".
```

**Comment by egeloen** [comment]
Weird... Can you try with:

``` yaml


ivory_ck_editor:
    inline: false
    default_config: "my_config"
    configs:
        my_config:
            toolbar: "my_toolbar_1"
            extraPlugins: "youtube,uploadimage"
    toolbars:
        configs:
            my_toolbar_1:
                # (...)
    plugins:
        youtube:
            path:     "/bundles/<MY_BUNDLE>/js/youtube/"
            filename: "plugin.js"
        uploadimage:
            path: "/bundles/<MY_BUNDLE>/js/uploadimage/plugin.js"
```
