### ISSUE TITLE
Advanced Tab

### ISSUE THREAD

**Issue by Xeyos88** [egeloen/IvoryCKEditorBundle#296]
Creating a custom configuration, how can remove the advanced tabs?

**Comment by egeloen** [comment]
@Xeyos88 What do you mean by tab? Toolbar?

**Comment by Xeyos88** [comment]
@egeloen Yes in toolbar, some options as image or link have an advanced tab, i would remove it.

**Comment by egeloen** [comment]
Take a look to http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/toolbar.html

**Comment by egeloen** [comment]
@Xeyos88 Does it help you?

**Comment by Xeyos88** [comment]
@egeloen No sorry, i would remove the Advanced tab in some options(e.g img, url)

**Comment by egeloen** [comment]
@Xeyos88 I'm not sure I have fully understand your question but given you want to remove the img & url tab icon, you just have to override the associated toolbar items. The built-in toolbar items are defined in the `ToolbarManager` class: https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Model/ToolbarManager.php#L24-L50

I thing when you're talking about img & url, you're refering to the `Link` and `Image` toolbar icons and we will consider you're using the full toolbar (but the same goes for the standard and basic ones):

``` yaml
ivory_ck_editor:
    configs:
        acme:
            toolbar: "full"
    toolbars:
        items:
            full.links: [ 'Anchor' ]
            full.insert: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'SpecialChar', 'Smiley', 'PageBreak', 'Iframe' ]
```

**Comment by Xeyos88** [comment]
![Image of Yaktocat](https://image.ibb.co/bz0Mnk/Schermata_del_2017_06_19_14_07_43.png)
I would remove this tab in all options.

**Comment by egeloen** [comment]
If you can point me the official CKEditor documentation about this feature, I can maybe help you

**Comment by Xeyos88** [comment]
i found this:
http://ckeditor.com/addon/dialogadvtab
http://ckeditor.com/forums/CKEditor-3.x/ckeditor-image-dialog-removing-advanced-tab

**Comment by egeloen** [comment]
@Xeyos88 The following do the trick:

``` yaml
ivory_ck_editor:
    configs:
        default:
            removeDialogTabs: "image:advanced"
```
