### ISSUE TITLE
Plugin installation problem

### ISSUE THREAD

**Issue by Xeyos88** [egeloen/IvoryCKEditorBundle#307]
I try to install http://ckeditor.com/addon/codeTag.
I put the folder dowloaded in web/bundles/ivoryckeditor/
and this is my configuration:
```yaml
 default_config: my_config
    configs:
        my_config:
            extraPugins: "codeTag"
            toolbar: [["Source", "-", "Undo", "Redo", "-", "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript",
                "RemoveFormat", "Code", "-","NumberedList", "BulletedList","-","JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock",
                "Link", "Unlink", "-", "Image", "Table", "-", "Blockquote", "HorizontalRule", "SpecialChar", "Smiley",
                "-", "TextColor", "BGColor"], "/", ["Styles", "Format", "Font", "FontSize", "Maximize", "Preview"]]
            removeDialogTabs: "image:advanced;link:advanced"
    plugins:
        codeTag:
          path: "web/bundles/ivoryckeditor/plugins/codeTag/plugin.js"
          filename: "plugin.js"
```
But doesn't work.
