### ISSUE TITLE
plugin colordialog doesn't work

### ISSUE THREAD

**Issue by guizme555** [egeloen/IvoryCKEditorBundle#316]
Hy all !
I have a problem to integrate option "TextColor" into my ToolBar.
Have you any ideas to solve this ? 
Thank's a lot

Here my config :
``` yaml
ivory_ck_editor:

    toolbars:
        configs:
          my_custom_toolbar: ["@tool", "/", "@styles"]
        items:
          styles: [ 'Styles','Format', 'TextColor']
          tool: ["Bold", "-", "Italic", "-","Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "RemoveFormat", "-", "NumberedList", "-", "BulletedList",'-','Outdent','Indent','-', "Blockquote" , "Image", "Link", "Unlink", "-", "Maximize", "Source"]
    default_config: default
    configs:
        default:
            toolbar: "my_custom_toolbar"
            filebrowserBrowseRoute: admin_app_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_app_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
                hide_context: true
                context: default
            filebrowserUploadRoute: admin_app_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
                hide_context: true
                context: default
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_app_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: default # Optional, to upload in a custom context
            format_tags: 'p;h1;h2;h3;h4;h5;pre'
```

Version : 4.0.6

**Comment by egeloen** [comment]
When using the following configuration, it is working as expected:

``` yaml
ivory_ck_editor:
    configs:
        default:
            toolbar: "my_custom_toolbar"
    toolbars:
        configs:
            my_custom_toolbar: ["@tool", "/", "@styles"]
        items:
            styles: [ 'Styles','Format', 'TextColor']
            tool: ["Bold", "-", "Italic", "-","Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "RemoveFormat", "-", "NumberedList", "-", "BulletedList",'-','Outdent','Indent','-', "Blockquote" , "Image", "Link", "Unlink", "-", "Maximize", "Source"]
```

![ckeditor](https://user-images.githubusercontent.com/737992/31055625-09ce502c-a6c6-11e7-8424-29f6313e1598.png)

**Comment by guizme555** [comment]
Thank's to your back.

For information it's works if only i add plugin's lines :

``` yaml
ivory_ck_editor:

    plugins:
        colorbutton:
            filename: 'plugin.js'
            path: '/bundles/sonataformatter/vendor/ckeditor/plugins/colorbutton/'
    toolbars:
        configs:
          my_custom_toolbar: ["@tool", "/", "@styles"]
        items:
          styles: [ 'Styles','Format', 'TextColor']
          tool: ["Bold", "-", "Italic", "-","Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "RemoveFormat", "-", "NumberedList", "-", "BulletedList",'-','Outdent','Indent','-', "Blockquote" , "Image", "Link", "Unlink", "-", "Maximize", "Source"]
    default_config: default
    configs:
        default:
            colorButton_colors: "474d55,ffffff"
            extraPlugins: "colorbutton"
            toolbar: "my_custom_toolbar"
            filebrowserBrowseRoute: admin_app_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_app_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
                hide_context: true
                context: default
            filebrowserUploadRoute: admin_app_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
                hide_context: true
                context: default
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_app_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: default # Optional, to upload in a custom context
            format_tags: 'p;h1;h2;h3;h4;h5;pre'
```
