### ISSUE TITLE
[CKEDITOR] Error code: editor-incorrect-destroy.

### ISSUE THREAD

**Issue by ikerib** [egeloen/IvoryCKEditorBundle#317]
Hi,
I'm having a problem with this bundle... I did use this bundle before (v4 and v5) but in this project it isn't working and I don't know why.

I had installed it correctly... but when I launch my app there is no CKEditor and I can see these error on the console. Any help?

This is my config:

```
ivory_ck_editor:
    configs:
        my_config_1:
            toolbar: "my_toolbar_1"
            uiColor: "#cccccc"
    toolbars:
        configs:
            my_toolbar_1: [ [ 'Bold', 'Italic', 'Underline', '-','NumberedList', 'BulletedList', '-', 'Outdent', 'Indent' ]]
            my_toolbar_2: [ [ "Source" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]

```

This is my entity:

```
    /**
     * @ORM\Column(name="value_text", type="text", nullable=true)
     */
    private $value_text;
```

This is my FormType:

```
use Ivory\CKEditorBundle\Form\Type\CKEditorType;
...
->add('value_text', CKEditorType::class, array(
                'config_name' => 'my_config_1',
            ))
```

I tried to disable all other JS from AdminLTE theme but still is not working...
Thanks in advance
