### ISSUE TITLE
styleSet.add config

### ISSUE THREAD

**Issue by pdesmarais** [egeloen/IvoryCKEditorBundle#48]
Hi there!

I'm trying to add styles to the styles menu in CKEditor. Trying to figure out how to add it to the default list while using the configuration method you explain in the docs of your bundle.

i tried with this :

``` yaml
ivory_ck_editor:
    configs:
        admin:
            uiColor:                "#000000"
            styleSet.add:           ( 'default', [
                                        { name: 'Just a test',      element: 'h2', styles: { 'font-style': 'italic' } }
                                    ])
```

but the yaml parser bugs out on the syntax...

I also tried with :

``` yaml
ivory_ck_editor:
    configs:
        admin:
            uiColor:                "#000000"
            styleSet.add:           { name : 'Strong Emphasis ProjectName', element : 'strong' }
```

and this :

``` yaml
ivory_ck_editor:
    configs:
        admin:
            uiColor:                "#000000"
            styleSet:           { name : 'Strong Emphasis ProjectName', element : 'strong' }
```

they both don't do anything...

Do you know how I should go about for this?

Thanks!
