### ISSUE TITLE
Templates plugin configuration

### ISSUE THREAD

**Issue by pdesmarais** [egeloen/IvoryCKEditorBundle#67]
Hi!

I added the templates plugin to CKEditor and it works fine. The only problem I'm having is figuring out how I can add templates from my config.yml. I've been trying with this config layout. The templates list is emptied (if I remove my template, the list is populate by the default values which are part of the plugin) which makes me think that I'm almost there, but my template doesn't appear in the list.

``` yml
extraPlugins: templates
templates :
    -
        title : 'My template'
        description : 'Description for my template'
        html : '<h2>Template 1</h2>'
```

Another example would be :

``` yml
extraPlugins: templates
templates :
    -
        title : 'My other template'
        description : 'Description for my other template'
        html : 
            -
                '<h2>Template 1</h2>'+
                '<small>Template 1</small>'
```

Any idea?
