### ISSUE TITLE
Default configuration not working

### ISSUE THREAD

**Issue by podolskis** [egeloen/IvoryCKEditorBundle#80]
Tried to setup default Ck configuration in yml, as described in manual:

```
ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
          toolbar: full
```

I'm getting errors, because undefined variables: "Warning: Invalid argument supplied for foreach() in /egeloen/ckeditor-bundle/Ivory/CKEditorBundle/Resources/views/Form/ckeditor_widget.html.php" lines 15/19/23
I'm not planing to use plugins, templates, or need custom styles, so I expect default configuration to prepare those needed variables and work out of the box.
